# Generated by Django 4.2.1 on 2023-05-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td_id', models.PositiveIntegerField(verbose_name='ID клиента')),
                ('name', models.TextField(verbose_name='Имя пользователя')),
                ('client_phone_number', models.TextField(verbose_name='Номер телефона клиента')),
            ],
            options={
                'verbose_name': 'Профиль',
            },
        ),
    ]
