# Generated by Django 4.2.1 on 2023-05-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя мастера')),
                ('working_hours', models.TextField(verbose_name='Расписание мастера')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название салона')),
                ('adress', models.TextField(verbose_name='Адрес салона')),
                ('salon_phone_number', models.TextField(verbose_name='Номер телефона салона')),
                ('master', models.TextField(verbose_name='Имя мастера')),
                ('service', models.TextField(verbose_name='Наименование услуги')),
                ('price', models.IntegerField(verbose_name='Цена услуги')),
                ('visit_time', models.TextField(verbose_name='Время визита')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='clients',
            name='td_id',
            field=models.PositiveIntegerField(verbose_name='telegram ID клиента'),
        ),
    ]
